[2020-10-09 10:45:40,640] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:46:42,790] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:47:02,360] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 10:47:02,361] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 10:48:57,367] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:48:58,654] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:49:11,698] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:49:11,701] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 10:50:16,562] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:50:17,996] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:51:21,045] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:51:22,038] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:51:32,755] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:51:32,761] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 10:52:41,444] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:52:42,548] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:52:50,138] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:52:50,139] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 10:52:59,995] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:52:59,998] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 10:53:55,412] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:53:56,773] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:54:06,465] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:54:06,467] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 10:55:59,618] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:56:01,061] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:56:32,595] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 10:56:33,258] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 10:56:45,594] [view.py:79] [view:get_predict_flow] [ERROR]- [dd159885-891f-4452-9267-66e662005a85]:Value must be a list, tuple, range or generator, or a dict. Supplied value is <class 'str'>
[2020-10-09 10:56:45,596] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-10-09 11:02:17,184] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:02:18,402] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:02:41,263] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:02:41,269] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:03:39,658] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:03:40,997] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:03:51,740] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:03:51,741] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:04:41,759] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:04:42,997] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:05:01,998] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:05:02,013] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:05:58,086] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:05:59,353] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:06:16,188] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:06:16,189] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:06:59,697] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:07:00,778] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:07:27,351] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:07:27,352] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:10:38,798] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:10:40,081] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:11:34,600] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:11:35,363] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:11:47,418] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:11:48,040] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:11:53,210] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:11:53,590] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:12:03,837] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:12:04,462] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:12:20,964] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:12:21,652] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:12:40,124] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:12:40,836] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:13:24,209] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:13:25,148] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:13:40,627] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:13:50,819] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:13:50,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:14:04,944] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:14:05,907] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:17:21,412] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:17:22,423] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:19:45,412] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:19:46,090] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:20:09,474] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:20:09,475] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:25:25,777] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:25:27,740] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:26:51,544] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:26:51,546] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:27:42,290] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:27:43,408] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:27:55,472] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:27:55,474] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:29:41,671] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:29:44,398] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:31:08,110] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:31:08,111] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-09 11:31:57,705] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 11:31:58,589] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:34:46,034] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:34:46,774] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:35:03,326] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:35:03,327] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:35:46,056] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:35:47,346] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:35:59,936] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:35:59,938] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:36:48,507] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:36:49,886] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:37:00,101] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:37:00,104] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:37:21,613] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:37:21,614] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:46:59,649] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:47:30,429] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:47:30,430] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:50:20,588] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:50:21,885] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:50:31,321] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:50:31,965] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:50:42,144] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:50:42,145] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:51:36,369] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:51:36,377] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:53:20,610] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:53:21,825] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:54:06,858] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:54:34,463] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:54:34,483] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:56:19,412] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:56:19,413] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:56:58,180] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:56:58,182] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:58:08,502] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 11:58:10,296] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 11:58:21,830] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:58:21,832] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 11:58:39,501] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 11:58:39,503] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:00:56,421] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:00:57,824] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:01:07,165] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:01:07,166] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:01:17,290] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:01:17,292] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:01:21,759] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:01:21,760] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:01:35,814] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:01:37,295] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:01:49,022] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:01:49,024] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:01:53,927] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:01:53,929] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:03:23,335] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:03:24,521] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:04:35,590] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:04:36,304] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:04:46,452] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:04:46,453] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:04:58,946] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:04:58,947] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:05:14,073] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:05:14,073] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:27:08,808] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:27:56,312] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:27:56,313] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:28:30,421] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:28:31,554] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:28:42,630] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:28:42,633] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:29:07,277] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:29:07,278] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:29:29,451] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:29:29,451] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:29:38,830] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:29:38,831] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:29:45,532] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:29:45,533] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:30:36,787] [view.py:54] [view:get_predict_flow] [INFO]- [dd159885-891f-4452-9267-66e662005a85]:请求成功，任务开始启动
[2020-10-09 12:30:36,788] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:30:44,953] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-09 12:30:46,430] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:32:53,298] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_min.py changed, reloading.
[2020-10-09 12:32:55,679] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:33:40,714] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-09 12:34:26,752] [view.py:54] [view:get_predict_flow] [INFO]- [f59794e2-e51d-46c2-b01a-b7950d22cd3b]:请求成功，任务开始启动
[2020-10-09 12:34:26,753] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:34:55,119] [view.py:54] [view:get_predict_flow] [INFO]- [f59794e2-e51d-46c2-b01a-b7950d22cd3b]:请求成功，任务开始启动
[2020-10-09 12:34:55,120] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:35:07,873] [view.py:54] [view:get_predict_flow] [INFO]- [f59794e2-e51d-46c2-b01a-b7950d22cd3b]:请求成功，任务开始启动
[2020-10-09 12:35:07,873] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:35:15,264] [view.py:54] [view:get_predict_flow] [INFO]- [f59794e2-e51d-46c2-b01a-b7950d22cd3b]:请求成功，任务开始启动
[2020-10-09 12:35:15,266] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:35:37,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:35:53,836] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:36:03,203] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:37:22,356] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:37:23,992] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:37:30,357] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:37:32,628] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:37:34,419] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:38:19,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:38:20,299] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:38:53,908] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-09 12:39:29,898] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:39:30,574] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:39:34,662] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:39:36,586] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:39:38,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:39:39,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:40:18,849] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-09 12:40:19,388] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:40:20,005] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:40:23,914] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:40:23,919] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:40:26,646] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:40:26,648] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:40:33,752] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:40:33,754] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:40:34,566] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:40:34,570] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:41:03,754] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:41:03,755] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:41:04,770] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:41:04,772] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:41:05,367] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:41:05,368] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:41:06,142] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:41:06,143] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:41:06,692] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(file)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 298, in __init__
    self.content = content
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 321, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 17: invalid start byte
[2020-10-09 12:41:06,694] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:42:03,215] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:42:03,905] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:42:07,734] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 0
[2020-10-09 12:42:12,256] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 0
[2020-10-09 12:42:13,178] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 0
[2020-10-09 12:44:09,470] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:44:10,263] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:44:16,579] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 5919
[2020-10-09 12:44:19,075] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 5919
[2020-10-09 12:44:21,019] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 5919
[2020-10-09 12:45:42,765] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:45:43,676] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:47:29,045] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:47:29,990] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:47:41,471] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:47:42,387] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:47:48,645] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(os.path.join(file_path, work_id + ".xlsx"), mimetype='application/vnd.ms-excel')
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 296, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
[2020-10-09 12:47:48,648] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:47:50,373] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(os.path.join(file_path, work_id + ".xlsx"), mimetype='application/vnd.ms-excel')
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 296, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
[2020-10-09 12:47:50,374] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:47:57,403] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    resp = HttpResponse(os.path.join(file_path, work_id + ".xlsx"))
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/response.py", line 296, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
[2020-10-09 12:47:57,404] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:47:57,868] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:47:58,912] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:48:04,488] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 116
[2020-10-09 12:50:03,295] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:50:04,594] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:50:10,225] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 12
[2020-10-09 12:50:13,152] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 12
[2020-10-09 12:51:59,281] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:52:00,285] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:52:07,447] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 26
[2020-10-09 12:52:09,526] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 26
[2020-10-09 12:52:10,339] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 26
[2020-10-09 12:52:33,776] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:52:34,747] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:52:44,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 26
[2020-10-09 12:53:31,628] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:53:32,679] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:53:39,736] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 839
[2020-10-09 12:54:15,550] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:54:16,600] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:54:23,471] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 172, in FileDown
    pd_data = pandas.read_excel(os.path.join(file_path, work_id + ".xlsx"), skiprows=[0] ,index=False)
  File "/Applications/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'
[2020-10-09 12:54:23,477] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:54:24,672] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 172, in FileDown
    pd_data = pandas.read_excel(os.path.join(file_path, work_id + ".xlsx"), skiprows=[0] ,index=False)
  File "/Applications/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'
[2020-10-09 12:54:24,673] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:54:25,642] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 172, in FileDown
    pd_data = pandas.read_excel(os.path.join(file_path, work_id + ".xlsx"), skiprows=[0] ,index=False)
  File "/Applications/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'
[2020-10-09 12:54:25,642] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:54:26,603] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 172, in FileDown
    pd_data = pandas.read_excel(os.path.join(file_path, work_id + ".xlsx"), skiprows=[0] ,index=False)
  File "/Applications/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'
[2020-10-09 12:54:26,604] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-09 12:54:32,669] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:54:33,976] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-09 12:54:41,237] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 839
[2020-10-09 12:54:59,225] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-09 12:55:19,757] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/f59794e2-e51d-46c2-b01a-b7950d22cd3b.xlsx HTTP/1.1" 200 5919
[2020-10-09 12:55:46,998] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-09 12:56:32,534] [view.py:55] [view:get_predict_flow] [INFO]- [75c5335d-d063-4cc0-9df0-9cc4097b0510]:请求成功，任务开始启动
[2020-10-09 12:56:32,535] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:57:09,919] [view.py:55] [view:get_predict_flow] [INFO]- [75c5335d-d063-4cc0-9df0-9cc4097b0510]:请求成功，任务开始启动
[2020-10-09 12:57:09,920] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:57:19,417] [view.py:55] [view:get_predict_flow] [INFO]- [75c5335d-d063-4cc0-9df0-9cc4097b0510]:请求成功，任务开始启动
[2020-10-09 12:57:19,418] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-09 12:57:53,043] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1035
[2020-10-09 12:58:04,306] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-09 12:58:17,557] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/75c5335d-d063-4cc0-9df0-9cc4097b0510.xlsx HTTP/1.1" 200 6001
[2020-10-09 12:58:38,112] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-09 12:58:39,548] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
